I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 46, in script
    background "black"
Exception: Sayer 'background' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 46, in script
    background "black"
  File "C:\Users\levio\Desktop\renpy-8.1.2-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\levio\Desktop\renpy-8.1.2-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'background' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.2.23090503
gameJam23 1.0
Thu Sep 21 20:01:40 2023
